# Docker Compose configuration for development
version: '3.8'

services:
  bankruptcy-prediction:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../outputs:/app/outputs
      - ../CompanyBankruptcyData.csv:/app/CompanyBankruptcyData.csv
      - ../src:/app/src
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # Note: Nginx service removed - configure separately if needed